# Generated by Django 3.1.2 on 2020-10-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('birthdate', models.DateField(null=True)),
            ],
            options={
                'db_table': 'stars',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('year', models.SmallIntegerField()),
                ('duration', models.SmallIntegerField(null=True)),
                ('actors', models.ManyToManyField(db_column=('id_movie', 'id_actor'), db_table='play', to='movieweb.Star')),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
