# Generated by Django 3.1.2 on 2020-10-27 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(db_column='id_director', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='movieweb.star'),
        ),
    ]
