# Generated by Django 3.1.2 on 2020-10-27 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieweb', '0002_movie_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(db_column=('id_movie', 'id_actor'), db_table='play', related_name='playedMovies', to='movieweb.Star'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(db_column='id_director', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directedMovies', to='movieweb.star'),
        ),
    ]
