# Generated by Django 3.1.2 on 2020-10-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieweb', '0003_auto_20201027_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
